version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Show the current nfiles limit after raising
          shell: sudo /bin/bash -eol pipefail
          command: |
              ulimit -n 65535
              sudo -u circleci ./runscript
       - run:
          name: Show the current nfiles limit again
          command: ulimit -n
