version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7
     steps:
       - checkout
       - run:
          name: Print the bash_env file
          command: cat $BASH_ENV
       - run:
          name: Add to the env
          command: echo "export EXTRA_ENV_FTW=allset" >> $BASH_ENV
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Print the environment
          command: env
