version: 2
jobs:
   build:
     docker:
       - image: circleci/python
     steps:
       - add_ssh_keys:
           fingerprints:
             - "ae:cf:10:c8:61:27:1a:fa:32:1c:f3:04:5a:e1:b6:a1"
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Try logging in with a key
          command: ssh testuser@vega.entropyonwheels.com w
