version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
          name: Allow a higher nfiles
          command: |
              sudo sh -c 'echo session required pam_limits.so >> /etc/pam.d/common-session'
              sudo sh -c 'echo *   hard    nfiles  65535 >> /etc/security/limits.conf'
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Show the current nfiles limit
          command: ulimit -n
       - run:
          name: Increase the nfiles limit
          command: ulimit -n 65535
          shell: /bin/bash -eol pipefail
       - run:
          name: Show the current nfiles limit again
          command: ulimit -n
