version: 2
jobs:
   build:
     docker:
       - image: circleci/python
     steps:
       - checkout
       - run:
          name: Print the environment
          command: env
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
