version: 2
jobs:
   build:
     docker:
       - image: circleci/python
     steps:
       - run:
          name: Print the environment
          command: env | sort
       - run:
          name: Export some variables
          command: |
            cat > <<EOF
            export TITI=`date +"%Y-%m-%d_%H-%M-%S"`
            export TITO=`date +"%Y-%m-%d_%H-%M-%S"`
            export TETE=$(date +"%Y-%m-%d_%H-%M-%S")
            EOF
       - run:
          name: Print the environment again
          command: env | sort
