version: 2
jobs:
   build:
     machine:
       enabled: true
     steps:
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Print the environment without setting BASH_ENV
          command: env
       - run:
          name: Print the environment
          command: env
          environment:
            - BASH_ENV: ~/project/extraenv
       - run:
          name: Run the pws function
          command: pws
            - BASH_ENV: ~/project/extraenv
