version: 2
jobs:
   build:
     machine:
       java:
         version: openjdk8
     steps:
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
