version: 2
jobs:
   build:
     machine:
       enabled: true
     steps:
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Print the environment
          command: env
          environment:
            - BASH_ENV: "extraenv"
