version: 2
jobs:
   build:
     docker:
       - image: circleci/python
     steps:
       - setup_remote_docker
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
