version: 2
jobs:
   build:
     docker:
       - image: circleci/python
       - image: stripemock/stripe-mock
     steps:
       - checkout
       - run:
          name: Say hello to the world
          command: echo "Hello, World!"
       - run:
          name: Wait for a while
          command: sleep 120
